name       : zpaq
version    : '7.15'
release    : 3
source     :
    - https://github.com/zpaq/zpaq/archive/7.15.tar.gz : 64280d86cd38ad5ebc1c6415b17eb09ee292078d772176b90e16287687191efe
license    :
    - MIT
    - Unlicense
component  : system.utils
summary    : zpaq is a free and open source incremental, journaling command-line archiver.
description: |
    zpaq is a free and open source incremental, journaling command-line archiver for Windows, Linux and Mac OS/X. Incremental means that when you back up your hard drive, then only those files whose last-modified date or size has changed since the previous backup are added. Journaling means that the archive is append-only. When you add files or directories to the archive, both the old and new versions are saved. You can recover old versions by specifying the date or version number.
    zpaq is faster and compresses better than most other popular archivers and backup programs, especially for realistic backups that have a lot of duplicate files and a lot of already compressed files.
build      : |
    %make CXXFLAGS="${CXXFLAGS}"
install    : |
    %make_install PREFIX=/usr
